gmf:
  replicaCount: 2

mapserver:
  replicaCount: 2

pods:
  services:
    mapserver:
      replicaCount: 2
    qgisserver:
      replicaCount: 2

qgisserver:
  replicaCount: 2

app:
  services:
    geoportal:
      replicaCount: 2

    mapserver:
      replicaCount: 2

    qgisserver:
      replicaCount: 2
