secrets:
  secrets:
    # https://httpd.apache.org/docs/2.4/mod/worker.html
    mpm_event.conf:
      value: |
        # event MPM
        # StartServers: initial number of server processes to start
        # MinSpareThreads: minimum number of worker threads which are kept spare
        # MaxSpareThreads: maximum number of worker threads which are kept spare
        # ThreadsPerChild: constant number of worker threads in each server process
        # MaxRequestWorkers: maximum number of worker threads
        # MaxConnectionsPerChild: maximum number of requests a server process serves
        <IfModule mpm_event_module>
                # default: 2
                StartServers             1
                # default: 25
                MinSpareThreads          1
                # default: 75
                MaxSpareThreads          1
                # default: 64
                ThreadLimit              1
                # default: 25
                ThreadsPerChild          1
                # default: 150
                MaxRequestWorkers        150
                MaxConnectionsPerChild   0

    # https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html
    mapserver.conf:
      value: |
        # MapServer has memory leaks, this limit should improve long term memory usage
        FcgidMinProcessesPerClass ${MIN_PROCESSES}
        FcgidMaxProcessesPerClass ${MAX_PROCESSES}
        FcgidMaxProcesses ${MAX_PROCESSES}
        FcgidBusyTimeout ${BUSY_TIMEOUT}
        FcgidIdleTimeout ${IDLE_TIMEOUT}
        FcgidIOTimeout ${IO_TIMEOUT}
        LimitRequestLine ${APACHE_LIMIT_REQUEST_LINE}
        FcgidProcessTableFile /tmp/fcgid_shm
        FcgidIPCDir /tmp/mod_fcgid

        ScriptAliasMatch "^${MAPSERVER_BASE_PATH}/(.*)" /usr/local/bin/mapserv_wrapper/$1
        ScriptAliasMatch "^${MAPSERVER_BASE_PATH}" /usr/local/bin/mapserv_wrapper
        <LocationMatch "^/.*">
          # Enable CORS (required for WFS requests)
          Header set Access-Control-Allow-Origin "*"
          Header set Cache-Control "max-age=0, must-revalidate, no-cache, no-store"

          SetHandler fcgid-script
          Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
          Require all granted
          Include /tmp/pass-env
        </LocationMatch>

        ExtendedStatus On
        <Location "/server-status-remote">
            SetHandler server-status
        </Location>

        ServerName localhost

    # https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html
    qgis.conf:
      value: |
        # QGIS has memory leaks, this limit should improve long term memory usage
        FcgidMinProcessesPerClass ${FCGID_MIN_PROCESSES}
        FcgidMaxProcessesPerClass ${FCGID_MAX_PROCESSES}
        FcgidMaxProcesses ${FCGID_MAX_PROCESSES}
        FcgidBusyTimeout ${FCGID_BUSY_TIMEOUT}
        FcgidIdleTimeout ${FCGID_IDLE_TIMEOUT}
        FcgidIOTimeout ${FCGID_IO_TIMEOUT}
        FcgidProcessTableFile /tmp/fcgid_shm
        FcgidIPCDir /tmp/mod_fcgid

        ScriptAliasMatch "^/.*" /usr/local/bin/qgis-mapserv-wrapper
        <LocationMatch "^/.*">
            SetHandler fcgid-script
            Require all granted
            Include /tmp/pass-env
            Header set Access-Control-Allow-Origin "*"
        </LocationMatch>

        ExtendedStatus On
        <Location "/server-status-remote">
            SetHandler server-status
        </Location>

        ServerName localhost
