secrets:
  external: true
  externalSecrets:
    data:
      C2C_AUTH_GITHUB_CLIENT_ID:
        remoteRef:
          key: c2c-auth-github-client-id
      C2C_AUTH_GITHUB_CLIENT_SECRET:
        remoteRef:
          key: c2c-auth-github-client-secret
      C2C_AUTH_GITHUB_SECRET:
        remoteRef:
          key: c2c-auth-github-secret
